services:
  # Local DynamoDB
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.2
    container_name: etiya-dynamodb-cont
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    healthcheck:
      test: ["CMD-SHELL", "java -jar DynamoDBLocal.jar -port 8000 -help > /dev/null || exit 0"]
      interval: 3s
      timeout: 3s
      retries: 3

  # Etiya's core app - Spring Cloud Function
  etiya-core:
    build: core/
    container_name: etiya-core-cont
    ports:
      - "8080:8080"
    depends_on:
      dynamodb-local:
        condition: service_healthy

