package licaza.etiya.core.service;

import static licaza.etiya.core.repository.ExerciseCatalogItemRepository.SHARED_CATALOG;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import licaza.etiya.core.exception.AlreadyExistsException;
import licaza.etiya.core.exception.ExerciseCatalogItemNotFoundException;
import licaza.etiya.core.exception.InputValidationException;
import licaza.etiya.core.model.ExerciseCatalogItem;
import licaza.etiya.core.repository.ExerciseCatalogItemRepository;
import licaza.etiya.core.service.validation.InputValidationService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

// A user sees the shared catalog plus the exercises they added themselves. Both use the same
// slug IDs, and where one ID is in both, the shared one wins
@Slf4j
@Service
public class ExerciseService {

  private final InputValidationService validatorService;
  private final ExerciseCatalogItemRepository repository;

  public ExerciseService(
      InputValidationService validatorService, ExerciseCatalogItemRepository repository) {
    this.validatorService = validatorService;
    this.repository = repository;
  }

  // What a user adds is theirs alone. A name the shared catalog already has is refused, so
  // nobody ends up with a private copy of a shared exercise
  public ExerciseCatalogItem registerExercise(String userId, ExerciseCatalogItem input) {
    validatorService.validate(input);

    // Always generated by the server, any ID in the request is ignored
    String generatedId = Slugs.of(input.getName());
    if (generatedId.isEmpty()) {
      throw new InputValidationException(
          "❌ Validation Error: Exercise name must contain letters or numbers");
    }
    input.setId(generatedId);
    input.setOwnerId(userId);
    log.debug("🆔 Generated new slug ID for exercise: {}", generatedId);

    if (repository.findById(SHARED_CATALOG, generatedId).isPresent() || !repository.create(input)) {
      throw new AlreadyExistsException(
          "EXERCISE_ALREADY_EXISTS",
          "❌ Error: The exercise with ID '" + generatedId + "' already exists.");
    }
    return input;
  }

  // Both filters are optional; the catalog is small, so the muscle group is filtered in memory.
  // The group is matched by name ignoring case, so ?muscleGroup=chest finds CHEST
  public List<ExerciseCatalogItem> searchExercises(
      String userId, String query, String muscleGroup) {
    log.info(
        "🔍 Querying database for exercises matching name: '{}' and muscle group: '{}'",
        query,
        muscleGroup);

    String slugPrefix = (query == null) ? "" : Slugs.of(query);

    // Sorted by ID, like each partition already is; the shared ones go in last so they win
    Map<String, ExerciseCatalogItem> byId = new TreeMap<>();
    for (String ownerId : new String[] {userId, SHARED_CATALOG}) {
      List<ExerciseCatalogItem> found =
          slugPrefix.isEmpty()
              ? repository.findAll(ownerId)
              : repository.findBySlugPrefix(ownerId, slugPrefix);
      found.forEach(e -> byId.put(e.getId(), e));
    }
    List<ExerciseCatalogItem> candidates = new ArrayList<>(byId.values());

    if (muscleGroup == null || muscleGroup.isBlank()) {
      return candidates;
    }
    return candidates.stream()
        .filter(
            e ->
                e.getMuscleGroup() != null
                    && muscleGroup.equalsIgnoreCase(e.getMuscleGroup().name()))
        .toList();
  }

  // Someone else's exercise is reported as missing, so their IDs can't be probed
  public ExerciseCatalogItem getExercise(String userId, String id) {
    return repository
        .findById(SHARED_CATALOG, id)
        .or(() -> repository.findById(userId, id))
        .orElseThrow(
            () ->
                new ExerciseCatalogItemNotFoundException(
                    "❌ Error: The exercise with ID '" + id + "' does not exist."));
  }
}
