# Detailed logs for local
logging.level.licaza.etiya.core=DEBUG
logging.level.software.amazon.awssdk=INFO

# Settings for local DynamoDB
aws.dynamodb.endpoint=http://dynamodb-local:8000
etiya.dynamodb.table-name=EtiyaWorkoutsApp
aws.region=us-east-1
