# Keep CloudWatch logs clean
logging.level.licaza.etiya.core=INFO
logging.level.software.amazon.awssdk=WARN

# Ignore Tomcat server, if present
spring.main.web-application-type=none

# DynamoDB table name, injected as a Lambda environment variable by CDK
etiya.dynamodb.table-name=${TABLE_NAME}
